import { Link } from '@inertiajs/react';
import { Timer, Mail, Lock, Eye, EyeOff, Globe, Github, Zap, LayoutDashboard, FileText, Shield } from 'lucide-react';

export default function Register() {
    return (
        <div className="flex min-h-screen">
            {/* Brand Panel */}
            <div className="flex-1 bg-violet-600 p-16 flex flex-col justify-between">
                {/* Top Section */}
                <div className="flex flex-col gap-12">
                    {/* Logo */}
                    <div className="flex items-center gap-2.5">
                        <div className="w-8 h-8 bg-white rounded-lg flex items-center justify-center">
                            <Timer className="w-5 h-5 text-violet-600" />
                        </div>
                        <span className="text-white font-jetbrains font-bold text-2xl">SheetThis</span>
                    </div>

                    {/* Hero Text */}
                    <div className="flex flex-col gap-4">
                        <h1 className="text-white font-inter font-bold text-5xl leading-tight">
                            Start tracking.<br />Start earning.
                        </h1>
                        <p className="text-[#A5B4FC] font-inter text-base leading-relaxed max-w-md">
                            Join thousands of freelancers who know exactly where every minute goes.
                        </p>
                    </div>

                    {/* Features */}
                    <div className="flex flex-col gap-4">
                        <div className="flex items-center gap-3">
                            <div className="w-9 h-9 bg-violet-500 rounded-lg flex items-center justify-center">
                                <Zap className="w-4 h-4 text-white" />
                            </div>
                            <span className="text-white font-inter text-sm font-medium">One-click time tracking across all projects</span>
                        </div>
                        <div className="flex items-center gap-3">
                            <div className="w-9 h-9 bg-violet-500 rounded-lg flex items-center justify-center">
                                <LayoutDashboard className="w-4 h-4 text-white" />
                            </div>
                            <span className="text-white font-inter text-sm font-medium">Visual reports and weekly timesheets</span>
                        </div>
                        <div className="flex items-center gap-3">
                            <div className="w-9 h-9 bg-violet-500 rounded-lg flex items-center justify-center">
                                <FileText className="w-4 h-4 text-white" />
                            </div>
                            <span className="text-white font-inter text-sm font-medium">Export timesheets for invoicing in one click</span>
                        </div>
                        <div className="flex items-center gap-3">
                            <div className="w-9 h-9 bg-violet-500 rounded-lg flex items-center justify-center">
                                <Shield className="w-4 h-4 text-white" />
                            </div>
                            <span className="text-white font-inter text-sm font-medium">Free forever for individuals — no credit card needed</span>
                        </div>
                    </div>
                </div>

                {/* Testimonial */}
                <div className="bg-[#2D2A5E] rounded-xl p-6 flex flex-col gap-3">
                    <p className="text-[#A5B4FC] font-inter text-sm italic leading-relaxed">
                        "I signed up on a Monday and had my first client invoice generated by Friday. SheetThis just works."
                    </p>
                    <div className="flex items-center gap-2.5">
                        <div className="w-8 h-8 rounded-full bg-emerald-400"></div>
                        <div className="flex flex-col gap-0.5">
                            <span className="text-white font-inter font-semibold text-[13px]">Sarah Chen</span>
                            <span className="text-[#A09ABF] text-xs font-inter">Freelance Product Designer</span>
                        </div>
                    </div>
                </div>
            </div>

            {/* Form Panel */}
            <div className="w-[540px] bg-white p-12 flex items-center justify-center">
                <div className="w-full max-w-sm flex flex-col gap-7">
                    {/* Form Header */}
                    <div className="flex flex-col gap-2">
                        <h2 className="text-gray-900 font-inter font-bold text-[28px]">Create your account</h2>
                        <p className="text-gray-700 font-inter text-sm">Start tracking time for free — no credit card required</p>
                    </div>

                    {/* Form Fields */}
                    <div className="flex flex-col gap-4">
                        {/* Name Row */}
                        <div className="flex gap-3">
                            <div className="flex-1 flex flex-col gap-1.5">
                                <label className="text-gray-500 text-[11px] font-inter font-semibold tracking-widest uppercase">First Name</label>
                                <div className="bg-[#F8F7FC] border border-gray-200 rounded-lg px-4 py-3">
                                    <span className="text-gray-400 font-inter text-sm">John</span>
                                </div>
                            </div>
                            <div className="flex-1 flex flex-col gap-1.5">
                                <label className="text-gray-500 text-[11px] font-inter font-semibold tracking-widest uppercase">Last Name</label>
                                <div className="bg-[#F8F7FC] border border-gray-200 rounded-lg px-4 py-3">
                                    <span className="text-gray-400 font-inter text-sm">Doe</span>
                                </div>
                            </div>
                        </div>

                        {/* Email Field */}
                        <div className="flex flex-col gap-1.5">
                            <label className="text-gray-500 text-[11px] font-inter font-semibold tracking-widest uppercase">Email Address</label>
                            <div className="flex items-center gap-2.5 bg-[#F8F7FC] border border-gray-200 rounded-lg px-4 py-3">
                                <Mail className="w-4 h-4 text-gray-400" />
                                <span className="text-gray-400 font-inter text-sm">you@email.com</span>
                            </div>
                        </div>

                        {/* Password Field */}
                        <div className="flex flex-col gap-1.5">
                            <label className="text-gray-500 text-[11px] font-inter font-semibold tracking-widest uppercase">Password</label>
                            <div className="flex items-center justify-between bg-[#F8F7FC] border border-gray-200 rounded-lg px-4 py-3">
                                <div className="flex items-center gap-2.5">
                                    <Lock className="w-4 h-4 text-gray-400" />
                                    <span className="text-gray-400 font-inter text-sm">Min. 8 characters</span>
                                </div>
                                <EyeOff className="w-4 h-4 text-gray-400 cursor-pointer" />
                            </div>
                        </div>

                        {/* Confirm Password Field */}
                        <div className="flex flex-col gap-1.5">
                            <label className="text-gray-500 text-[11px] font-inter font-semibold tracking-widest uppercase">Confirm Password</label>
                            <div className="flex items-center justify-between bg-[#F8F7FC] border border-gray-200 rounded-lg px-4 py-3">
                                <div className="flex items-center gap-2.5">
                                    <Lock className="w-4 h-4 text-gray-400" />
                                    <span className="text-gray-400 font-inter text-sm">••••••••••</span>
                                </div>
                                <EyeOff className="w-4 h-4 text-gray-400 cursor-pointer" />
                            </div>
                        </div>

                        {/* Terms Checkbox */}
                        <div className="flex items-center gap-2">
                            <div className="w-[18px] h-[18px] border border-gray-300 rounded bg-[#F8F7FC]"></div>
                            <span className="text-gray-600 font-inter text-xs">I agree to the Terms of Service and Privacy Policy</span>
                        </div>
                    </div>

                    {/* Actions */}
                    <div className="flex flex-col gap-4">
                        <button className="w-full bg-violet-600 hover:bg-violet-700 transition-colors text-white font-inter font-semibold text-[15px] py-3.5 rounded-lg">
                            Create Account
                        </button>

                        {/* Divider */}
                        <div className="flex items-center gap-4">
                            <div className="flex-1 h-px bg-gray-200"></div>
                            <span className="text-gray-400 text-[11px] font-inter font-semibold tracking-widest uppercase">Or</span>
                            <div className="flex-1 h-px bg-gray-200"></div>
                        </div>

                        {/* Social Buttons */}
                        <div className="flex gap-3">
                            <button className="flex-1 border border-gray-200 rounded-lg px-4 py-3 flex items-center justify-center gap-2 hover:bg-gray-50 transition-colors">
                                <Globe className="w-4 h-4 text-gray-500" />
                                <span className="text-gray-600 font-inter text-[13px] font-medium">Google</span>
                            </button>
                            <button className="flex-1 border border-gray-200 rounded-lg px-4 py-3 flex items-center justify-center gap-2 hover:bg-gray-50 transition-colors">
                                <Github className="w-4 h-4 text-gray-500" />
                                <span className="text-gray-600 font-inter text-[13px] font-medium">GitHub</span>
                            </button>
                        </div>
                    </div>

                    {/* Login Link */}
                    <div className="flex justify-center gap-1.5">
                        <span className="text-gray-600 font-inter text-[13px]">Already have an account?</span>
                        <Link href="/login" className="text-gray-900 font-inter text-[13px] font-semibold hover:underline">
                            Sign in
                        </Link>
                    </div>
                </div>
            </div>
        </div>
    );
}
