import { Testimonial } from '@/Components/Auth/Testimonial';
import { Checkbox } from '@/Components/Form/Checkbox';
import { PasswordToggle } from '@/Components/Form/PasswordToggle';
import { TextInput } from '@/Components/Form/TextInput';
import AuthLayout from '@/Layouts/AuthLayout';
import { privacyPolicy } from '@/routes';
import { index as login } from '@/routes/login';
import { store } from '@/routes/register';
import { Form, Link } from '@inertiajs/react';
import { FileText, LayoutDashboard, Lock, LucideIcon, Mail, Shield, User, Zap } from 'lucide-react';
import { useState } from 'react';

const FEATURES: { icon: LucideIcon; text: string }[] = [
    { icon: Zap, text: 'One-click time tracking across all projects' },
    { icon: LayoutDashboard, text: 'Visual reports and weekly timesheets' },
    { icon: FileText, text: 'Export timesheets for invoicing in one click' },
    { icon: Shield, text: 'Free forever for individuals — no credit card needed' },
];

export default function Register() {
    const [showPassword, setShowPassword] = useState(false);
    const [showConfirm, setShowConfirm] = useState(false);

    const hero = (
        <>
            <div className="flex flex-col gap-4">
                <h1 className="text-white font-inter font-bold text-5xl leading-tight">
                    Start tracking.<br />Start earning.
                </h1>
                <p className="text-brand-muted font-inter text-base leading-relaxed max-w-md">
                    Join thousands of freelancers who know exactly where every minute goes.
                </p>
            </div>
            <div className="flex flex-col gap-4">
                {FEATURES.map(({ icon: Icon, text }) => (
                    <div key={text} className="flex items-center gap-3">
                        <div className="w-9 h-9 bg-accent rounded-lg flex items-center justify-center shrink-0">
                            <Icon className="w-4 h-4 text-white" />
                        </div>
                        <span className="text-white font-inter text-sm font-medium">{text}</span>
                    </div>
                ))}
            </div>
        </>
    );

    const aside = (
        <Testimonial
            quote="“I signed up on a Monday and had my first client invoice generated by Friday. SheetThis just works.”"
            name="Sarah Chen"
            role="Freelance Product Designer"
            avatarClassName="bg-emerald-400"
        />
    );

    return (
        <AuthLayout hero={hero} aside={aside} formPaddingClassName="py-12">
            <Form className="flex flex-col gap-7" action={store()} method="post">
                {({ errors, processing }) => (
                    <>
                        <div className="flex flex-col gap-2">
                            <h2 className="text-gray-900 font-inter font-bold text-[28px]">Create your account</h2>
                            <p className="text-gray-500 font-inter text-sm">Start tracking time for free — no credit card required</p>
                        </div>

                        <div className="flex flex-col gap-4">
                            <TextInput
                                id="name"
                                name="name"
                                type="text"
                                label="Name"
                                icon={User}
                                placeholder="John Doe"
                                required
                                maxLength={191}
                                autoComplete="name"
                                error={errors.name}
                            />

                            <TextInput
                                id="email"
                                name="email"
                                type="email"
                                label="Email Address"
                                icon={Mail}
                                placeholder="you@email.com"
                                required
                                maxLength={191}
                                autoComplete="email"
                                error={errors.email}
                            />

                            <TextInput
                                id="password"
                                name="password"
                                type={showPassword ? 'text' : 'password'}
                                label="Password"
                                icon={Lock}
                                placeholder="Min. 8 characters"
                                required
                                autoComplete="new-password"
                                error={errors.password}
                                trailing={<PasswordToggle visible={showPassword} onToggle={() => setShowPassword((v) => !v)} />}
                            />

                            <TextInput
                                id="password_confirmation"
                                name="password_confirmation"
                                type={showConfirm ? 'text' : 'password'}
                                label="Confirm Password"
                                icon={Lock}
                                placeholder="••••••••••"
                                required
                                autoComplete="new-password"
                                error={errors.password_confirmation}
                                trailing={<PasswordToggle visible={showConfirm} onToggle={() => setShowConfirm((v) => !v)} />}
                            />

                            <Checkbox
                                id="terms"
                                name="terms"
                                value="1"
                                error={errors.terms}
                                label={
                                    <span className="text-gray-600 text-xs">
                                        I agree to the Terms of Service and{' '}
                                        <Link href={privacyPolicy()} className="text-accent font-medium hover:underline">
                                            Privacy Policy
                                        </Link>
                                    </span>
                                }
                            />
                        </div>

                        <button
                            type="submit"
                            disabled={processing}
                            className="w-full bg-accent hover:bg-accent/90 disabled:opacity-60 transition-colors text-white font-inter font-semibold text-[15px] py-3.5 rounded-lg cursor-pointer"
                        >
                            {processing ? 'Creating account…' : 'Create Account'}
                        </button>

                        <div className="flex justify-center gap-1.5">
                            <span className="text-gray-400 font-inter text-[13px]">Already have an account?</span>
                            <Link href={login()} className="text-accent font-inter text-[13px] font-semibold hover:underline">
                                Sign in
                            </Link>
                        </div>
                    </>
                )}
            </Form>
        </AuthLayout>
    );
}
